services:
  - type: web
    name: body-transformation-tracker
    runtime: static
    staticPublishPath: ./
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /
        destination: /transformation.html
